### PR TITLE
Early clicks in Ultrasequencer can count when the mod thinks it doesn't

### LINKED ISSUE #1942: Early clicks in Ultrasequencer can count when the mod thinks it doesn't
### What happened?

With the Ultrasequencer minigame (experimentation table) there's a brief window where you can click the first one but the mod thinks that clicks don't count yet, which breaks it and causes it to still recommend the first one when the second one is actually next. This leads to failing the minigame when following the mod.

It's easy to reproduce if you spam click the first one (with "block incorrect clicks" on, unsure if that's needed?) until the round starts.

### Screenshots

Image

### Log output

_No response_

### Minecraft Version

1.21.11

### Skyblocker Version

skyblocker-5.10.0+1.21.10.jar

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Kazzyyyyyyyy**
# Fixes #1942

Added early-interaction-block for the Ultrasequencer when it doesnt take clicks yet

## Changes:
 - added if statement and block to prevent early clicks, that caused this bug to happen

## Bug:
Click on the first element, right when the show animation is done (only once if 'Block Incorrect Clicks' is turned off). When done correctly (time window is pretty small), the solver thinks the current number is still 1, even though you already clicked it. If you then click 1 again, it will fail the puzzle. If 'Block Incorrect Clicks' is off, you can continue playing like normal, even though the highlighting will be stuck at the first item. Otherwise, if its turned on, you cant continue playing and will/need to fail the puzzle.

**Notes:**
 - the sequence must be at least 2 items long
 - when the bug happened, it is only for the sequence your currently on

## Testing the fix:
Tested it with several 'Ultrasequencer (Metaphysical)' runs, with 'Block Incorrect Clicks' both enabled and disabled. Tried reproducing the bug multiple times, without success.

### CODE REVIEW

**Review by kevinthegreat1 — COMMENTED** [review]
I think you should return should block incorrect clicks, in case people don’t want the mod to be messing with their clicks.

**Comment by Kazzyyyyyyyy** [comment]
Yes, but that would only resolve the Issue when 'shouldBlockIncorrectClicks' is true, when its false the bug would still appear as normal. I have a different solution in mind that would fix the click restriction but is definitely more complex. You tell me, you have a lot more experience here.

**Comment by kevinthegreat1** [comment]
I know that my proposed change will only make this bug fix available when that setting is on, but I don’t like the idea of this mod blocking clicks (without opt-in). Please change it to return should block incorrect clicks. I am open to hearing any other arguments if anyone has any.

File: src/main/java/de/hysky/skyblocker/skyblock/experiment/UltrasequencerSolver.java [hunk 1]
```diff
@@ -105,18 +105,15 @@ public List<ColorHighlight> getColors(Int2ObjectMap<ItemStack> slots) {
...
-				getSlots().int2ObjectEntrySet().stream()
-						.filter(entry -> entry.getValue().getCount() == count)
-						.findAny()
-						.map(Int2ObjectMap.Entry::getIntKey)
-						.ifPresent(nextSlot -> this.ultrasequencerNextSlot = nextSlot);
-			} else {
-				return shouldBlockIncorrectClicks();
-			}
-		}
+		if (getState() != State.SHOW) { return true; }  // Block early clicks when table is still loading
```
Comment (kevinthegreat1) [inline src/main/java/de/hysky/skyblocker/skyblock/experiment/UltrasequencerSolver.java]:
```suggestion
		if (getState() != State.SHOW) { return shouldBlockIncorrectClicks(); }  // Block early clicks when table is still loading
```
