### PR TITLE
Zealot lag fix

### LINKED ISSUE #1938: Special Zealot glow detection is unnecessarily laggy
### What happened?

[https://spark.lucko.me/vpvgLQmMCe](https://spark.lucko.me/vpvgLQmMCe)

The primary offender seems to be `TheEnd.isZealot()`. This function is so laggy because it has to perform an entity query for named armor stands above the enderman. A lesser source of lag inside the function is the getDimensions check which has to perform a hashmap lookup - this could probably be cached.

The most performant option would be to remove the `isZealot` call entirely, since special zealots are the only enderman that can hold end portal frames.

Addendum: one might think that since glow color is cached, this is not a problem:
```
public static boolean hasOrComputeMobGlow(Entity entity) {
	if (CACHE.containsKey(entity)) {
		return true;
	}
	int color = computeMobGlow(entity);
	if (color != NO_GLOW) {
		CACHE.put(entity, color);
		return true;
	}
	return false;
}
```
However, this caching does almost nothing! Note that the entity is only added to the cache *if it has a glow*. This means that entities that don't have a glow must be re-checked every frame regardless.

### Screenshots

Image

### Log output

_No response_

### Minecraft Version

1.21.6-1.21.8

### Skyblocker Version

Skyblocker 5.9.1 for 1.21.8

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kevinthegreat1**
Fix #1938. Untested.

### CODE REVIEW

**Review by Alex33856 — APPROVED** [review]

File: src/main/java/de/hysky/skyblocker/skyblock/end/TheEnd.java [hunk 1]
```diff
@@ -173,15 +173,12 @@ public static void onSpecialZealot() {
...
+		List<ArmorStand> entities = CLIENT.level.getEntitiesOfClass(
 				ArmorStand.class,
-				enderman.getDimensions(null).makeBoundingBox(enderman.position()).inflate(1),
+				enderman.getDimensions(enderman.getPose()).makeBoundingBox(enderman.position()).inflate(1),
 				armorStandEntity -> armorStandEntity.getName().getString().toLowerCase(Locale.ENGLISH).contains("zealot"));
-		if (entities.isEmpty()) {
-			return false;
-		}
-		return entities.getFirst().getName().getString().toLowerCase(Locale.ENGLISH).contains("zealot");
+		return !entities.isEmpty();
```
Comment (kevinthegreat1) [inline src/main/java/de/hysky/skyblocker/skyblock/end/TheEnd.java:181]: Doesn’t all entities have armor stands? This check is basically useless now.

Comment (Alex33856) [reply src/main/java/de/hysky/skyblocker/skyblock/end/TheEnd.java:181]: It's still useful since we need to differentiate between Zealots and other endermen. 
This just removes checking the name again since it is already done in the predicate.

Comment (kevinthegreat1) [reply src/main/java/de/hysky/skyblocker/skyblock/end/TheEnd.java:181]: Oh I’b blind.
