### PR TITLE
Fix a lot of config crashes because of null values

### LINKED ISSUE #890: Crash when opening the settings
### Minecraft Version

1.21.0

### Skyblocker Version

skyblocker-1.21.1-beta-da041ea+1.21 

### Reproduction Steps

Run the game, open settings, and it crashes.

### Crash Report file and latest.log

```shell
[11:04:04] [Render thread/INFO]:
 Generating YACL screen
[11:04:04] [Render thread/ERROR]:
 Reported exception thrown!
	at net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) ~[lwjgl-glfw-3.3.3.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:184) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1310) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.inputField" is null
	at dev.isxander.yacl3.gui.controllers.string.StringControllerElement.getValueText(StringControllerElement.java:461) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.controllers.string.StringControllerElement.setDimension(StringControllerElement.java:436) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.controllers.string.StringControllerElement.<init>(StringControllerElement.java:45) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.controllers.string.IStringController.provideWidget(IStringController.java:42) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.OptionListWidget.refreshOptions(OptionListWidget.java:75) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.OptionListWidget.<init>(OptionListWidget.java:40) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.YACLScreen$CategoryTab.<init>(YACLScreen.java:359) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.YACLScreen.lambda$init$4(YACLScreen.java:89) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source) ~[?:?]
	at dev.isxander.yacl3.gui.YACLScreen.method_25426(YACLScreen.java:90) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1143) ~[client-intermediary.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.openConfig(ModListEntry.java:185) ~[modmenu-11.0.1.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25402(ModListEntry.java:175) ~[modmenu-11.0.1.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25402(ModListWidget.java:298) ~[modmenu-11.0.1.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 14 more
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AzureAaron**
Fixes crashes related to fields in the config being serialized to null because of downgrades, whether YACL is going to do anything about this is unknown as they don't really support sub-classes so intervention on our end is an absolute necessity to stop end users from not being able to configure/use the mod fully.

If a config field is null at runtime then it gets reset back to the default and saved to the config file.

Fixes #890

### CODE REVIEW

**Review by viciscat — APPROVED** [review]

**Review by kevinthegreat1 — CHANGES_REQUESTED** [review]
This only happens in a very specific scenario, see #909. I don't think all this reflection is necessary.

**Comment by AzureAaron** [comment]
> This only happens in a very specific scenario, see #909. I don't think all this reflection is necessary.

What you haven't considered (as said on discord) is when the fields are serialized but as `null` which can happen if the field was missing from the file when the config was loaded and the mod saves the config through other means (e.g. item customization) in which case the issue would not be fixed by #909. So this is still needed to stop crashes.

File: src/main/java/de/hysky/skyblocker/config/ConfigNullFieldsFix.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+				Object targetValue = field.get(target);
+				Object sourceValue = field.get(source);
+
+				if (targetValue == null && sourceValue != null) {
+					field.set(target, sourceValue);
+				} else if (isFixable(field.getType())) {
+					if (targetValue != null && sourceValue != null) {
+						fixNullFields(targetValue, sourceValue);
+					}
+				}
```
Comment (LifeIsAParadox) [inline src/main/java/de/hysky/skyblocker/config/ConfigNullFieldsFix.java:50]: I think it would be smarter to first look if `targetvalue` and `sourcevalue` are not null before doing isfixable to avoid unnecessary calculations.
```suggestion
				} else if (targetValue != null && sourceValue != null && isFixable(field.getType())) {
						fixNullFields(targetValue, sourceValue);
					}
				}
```

**Review by LifeIsAParadox — CHANGES_REQUESTED** [review]

**Review by LifeIsAParadox — APPROVED** [review]
