### PR TITLE
Fix paul's minister perk not being accounted for

### LINKED ISSUE #922: Paul's minister perk is unaccounted for
### What happened?

If Paul is elected as a minister perk with the minister perk being the +10 score then the dungeon score calculator does not add the bonus.

### Screenshots

_No response_

### Log output

_No response_

### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

skyblocker-1.21.1+1.21.1.jar

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Emirlol**
Fixes #922
Not tested.

### CODE REVIEW

File: src/main/java/de/hysky/skyblocker/utils/Utils.java [hunk 1]
```diff
@@ -524,11 +533,12 @@ private static void tickMayorCache() {
...
             }
-            return ""; //Have to return a value for the thenAccept block.
+            return new JsonObject(); //Have to return a value for the thenAccept block.
         }).thenAccept(result -> {
             if (!result.isEmpty()) {
-                mayor = result;
-                LOGGER.info("[Skyblocker] Mayor set to {}.", mayor);
+                mayor = result.get("name").getAsString();
+                minister = result.getAsJsonObject("minister").get("name").getAsString();
+                LOGGER.info("[Skyblocker] Mayor set to {}, minister set to {}.", mayor, minister);
```
Comment (viciscat) [inline src/main/java/de/hysky/skyblocker/utils/Utils.java:541]: does it need to be logged? LOGGER.debug maybe?

Comment (Emirlol) [reply src/main/java/de/hysky/skyblocker/utils/Utils.java:541]: I think it's nice to have it in the logs for when someone provides logs for some bug. If it's not in the logs it could help identify the cause faster, and it's only really called once per gameplay session anyway.

Comment (AzureAaron) [reply src/main/java/de/hysky/skyblocker/utils/Utils.java:541]: I think we should look for the actual perk rather than just the mayor/minister themselves

**Comment by Emirlol** [comment]
Actually I'm not sure if the minister perk is always the same for a given mayor candidate. Might have to store perks and check if Paul's `EZPZ` perk is matched.

File: src/main/java/de/hysky/skyblocker/utils/Utils.java (hunk 1 above)
Comment (Emirlol) [reply src/main/java/de/hysky/skyblocker/utils/Utils.java]: Marking as resolved because of [`37136d1`](https://github.com/SkyblockerMod/Skyblocker/pull/923/commits/37136d199a74d2dff5c27632170c7a3a5a2944e4)

File: src/main/java/de/hysky/skyblocker/utils/mayor/MayorUtils.java [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+			if (!result.isEmpty()) {
+				mayor = new Mayor(result.get("key").getAsString(),
+						result.get("name").getAsString(),
+						result.getAsJsonArray("perks")
+						      .asList()
+						      .stream()
+						      .map(JsonElement::getAsJsonObject)
+						      .map(object -> new Perk(object.get("name").getAsString(), object.get("description").getAsString()))
+						      .toList());
+				JsonObject ministerObject = result.getAsJsonObject("minister");
```
Comment (AzureAaron) [inline src/main/java/de/hysky/skyblocker/utils/mayor/MayorUtils.java:85]: Special mayor elections don't have ministers, I would check if the field is present to prevent potential NPEs

**Review by AzureAaron — CHANGES_REQUESTED** [review]

File: src/main/java/de/hysky/skyblocker/utils/mayor/MayorUtils.java (hunk 2 above)
Comment (AzureAaron) [reply src/main/java/de/hysky/skyblocker/utils/mayor/MayorUtils.java:85]: Disclaimer: I have no clue what the field has when a special mayor is active since API is new we may wanna check later this month

File: src/main/java/de/hysky/skyblocker/utils/mayor/MayorUtils.java [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+				minister = new Minister(ministerObject.get("key").getAsString(),
+						ministerObject.get("name").getAsString(),
+						ministerObject.getAsJsonArray("perk")
```
Comment (AzureAaron) [inline src/main/java/de/hysky/skyblocker/utils/mayor/MayorUtils.java:88]: Hypixel has changed this to a json object

**Review by AzureAaron — CHANGES_REQUESTED** [review]

File: src/main/java/de/hysky/skyblocker/utils/mayor/MayorUtils.java (hunk 3 above)
Comment (Emirlol) [reply src/main/java/de/hysky/skyblocker/utils/mayor/MayorUtils.java]: Fixed in [`c781052`](https://github.com/SkyblockerMod/Skyblocker/pull/923/commits/c7810521aa4c2f3ac12948b1c67df9ede5c1b850).

**Review by AzureAaron — APPROVED** [review]
