### PR TITLE
Fix unknown found fairy soul locations resetting other found fairy souls

### LINKED ISSUE #1623: Islands with uncollected fairy souls sometimes reset found fairy soul waypoints
### What happened?

On islands where I do not have every fairy soul yet sometimes the fairy soul waypoints will reset and show me fairy souls that I have already collected. To be clear - I have previously clicked on the fairy soul **with the mod already installed** and the waypoint disappeared at the time, **but reappeared later**.

### Screenshots

Image

Image

### Log output

[latest.log](https://github.com/user-attachments/files/22061765/latest.log)

### Minecraft Version

1.21.6-1.21.8

### Skyblocker Version

skyblocker-5.7.0+1.21.8.jar

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rafern**
After the NEU repository was updated (I was using a very outdated fork for reasons that I don't remember), most of my fairy soul progress was reset. Restoring the `found_fairy_souls.json` file from a backup would also not work. It turns out that the mod was failing to load all found fairy soul locations after encountering a location that it didn't recognise, which can happen normally when fairy souls are moved. This PR makes it so that unknown locations are skipped instead of throwing an exception, and prints a warning in the console.

Note that a test is failing (`testToSkyblocker()`) after I made these changes. Everything is working fine for me, so I assumed that this was harmless. I don't understand how this test works, so if you could please look into it or let me know how to do it I would greatly appreciate. Thanks!

This might fix #1623 

Before:
image
image

After (note that there's now only a waypoint for the fairy soul that was moved, from #1272 ):
image
image
image

### CODE REVIEW

File: src/main/java/de/hysky/skyblocker/skyblock/waypoint/FairySouls.java [hunk 1]
```diff
@@ -81,7 +81,12 @@ private static void loadFairySouls() {
                     for (Map.Entry<String, JsonElement> foundFairiesForLocationJson : foundFairiesForProfileJson.getValue().getAsJsonObject().asMap().entrySet()) {
                         Map<BlockPos, ProfileAwareWaypoint> fairiesForLocation = fairySouls.get(foundFairiesForLocationJson.getKey());
                         for (JsonElement foundFairy : foundFairiesForLocationJson.getValue().getAsJsonArray().asList()) {
-                            fairiesForLocation.get(PosUtils.parsePosString(foundFairy.getAsString())).setFound(foundFairiesForProfileJson.getKey());
+							@Nullable ProfileAwareWaypoint waypoint = fairiesForLocation.get(PosUtils.parsePosString(foundFairy.getAsString()));
```
Comment (kevinthegreat1) [inline src/main/java/de/hysky/skyblocker/skyblock/waypoint/FairySouls.java]:
```suggestion
							ProfileAwareWaypoint waypoint = fairiesForLocation.get(PosUtils.parsePosString(foundFairy.getAsString()));
```

Comment (rafern) [reply src/main/java/de/hysky/skyblocker/skyblock/waypoint/FairySouls.java]: Done. So I'm guessing I should only use `@Nullable` for arguments and return values?
Edit: and fields

Comment (kevinthegreat1) [reply src/main/java/de/hysky/skyblocker/skyblock/waypoint/FairySouls.java]: Yeah. Sorry for not making it clear.

**Review by kevinthegreat1 — APPROVED** [review]
