### PR TITLE
Fix clicking in Ultrasequencer

### LINKED ISSUE #566: Can't click in Ultrasequencer
### What happened?

While using Skyblocker 1.18.0 it is impossible to do the Ultrasequencer add-on in the Experimentation Table. Every click is blocked even if the Ultrasequencer solver is disabled.

### Screenshots

_No response_

### Log output

_No response_

### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.18.0+1.20.4.jar

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kevinthegreat1**
Fix clicking in Ultrasequencer.  
Refactor click handling.

Fixes #566

### CODE REVIEW

File: src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java [hunk 1]
```diff
@@ -107,6 +120,8 @@ private static void updateItemMap(String visitorName, String lore) {
     }
 
     private static void drawScreenItems(DrawContext context, TextRenderer textRenderer, int mouseX, int mouseY) {
+        context.getMatrices().push();
+        context.getMatrices().translate(0, 0, 232);
```
Comment (AzureAaron) [inline src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java:124]: Any particular reason as to why 232 is used?

**Review by AzureAaron — DISMISSED** [review]

File: src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java (hunk 1 above)
Comment (kevinthegreat1) [reply src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java:124]: Same as cursor stack.

Comment (AzureAaron) [reply src/main/java/de/hysky/skyblocker/skyblock/garden/VisitorHelper.java]: The text for the count can still be covered by an item, perhaps try 400?

**Review by AzureAaron — APPROVED** [review]
