### PR TITLE
Waypoints refactor

### LINKED ISSUE #1024: waypoints not working
### What happened?

coordinate waypoints dont work outside of CH lobbies 

### Log output

_No response_

### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

skyblocker-1.22.2-beta-3b344cd+1.21.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kevinthegreat1**
## Highlights

Ordered waypoints have been migrated to waypoints gui.  
* All ordered waypoints made with commands will be migrated to waypoints.
* All commands have been removed except for importing the Skyblocker Ordered Waypoints format, which will be immediately migrated to waypoints gui once imported.
* Skyblocker Ordered Waypoints format is now unused.  

New Skyblocker Waypoints format
* Similar to the existing Skyblocker Ordered Waypoints format but more extensible.

## API Design

The "wither" pattern is employed. Each class extending `Waypoint` should override all "wither" methods to return a new instance of the subclass to ensure the runtime type of the waypoint is correct.

## API Changes

I have tried to keep API changes to a minimum, but here are the breaking changes:
* `Waypoint#setShouldRender` has been renamed to `Waypoint#setEnabled`.  
* `Waypoint#getColorComponents` has been renamed to `Waypoint#getRenderColorComponents`.  
* `Waypoint#render` now checks `Waypoint#shouldRender`.
  * This allows only rendering the name by overriding `shouldRender` to false and `shouldRenderName` to true.
* `NamedWaypoint#shouldRenderName` now defaults to `Waypoint#shouldRender`.
  * You now need to override `shouldRenderName` to always render the name.

## Bug Fixes
* Fixed waypoint groups with invalid locations never showing up in the edit screen but possibly rendered.
* Closes #1024.

### CODE REVIEW

**Review by viciscat — DISMISSED** [review]
Looks good I suppose but did not test, might do that at some point.

**Comment by kevinthegreat1** [comment]
I’ll wait for aaron to look at this pr.

File: src/main/java/de/hysky/skyblocker/skyblock/waypoint/OrderedWaypoints.java [hunk 1]
```diff
@@ -1,309 +1,90 @@
...
-	private static final Semaphore SEMAPHORE = new Semaphore(1);
-	private static final Object2IntOpenHashMap<String> INDEX_STORE = new Object2IntOpenHashMap<>();
-	private static final int RADIUS = 2;
-	private static final float[] LIGHT_GRAY = { 192 / 255f, 192 / 255f, 192 / 255f };
-
-	private static CompletableFuture<Void> loaded;
-	private static boolean showAll;
+	public static final Path PATH = SkyblockerMod.CONFIG_DIR.resolve("ordered_waypoints.json");
 
 	public static void init() {
```
Comment (AzureAaron) [inline src/main/java/de/hysky/skyblocker/skyblock/waypoint/OrderedWaypoints.java:53]: Why did the @Init annotation disappear? was this not rebased?

File: src/main/java/de/hysky/skyblocker/skyblock/waypoint/OrderedWaypoints.java [hunk 2]
```diff
@@ -1,309 +1,90 @@
...
-			} catch (Exception e) {
-				LOGGER.error("[Skyblocker Ordered Waypoints] Failed to load the waypoints! :(", e);
-			}
-		});
-	}
-
-	private static void save() {
-		try (BufferedWriter writer = Files.newBufferedWriter(PATH)) {
-			SkyblockerMod.GSON.toJson(SERIALIZATION_CODEC.encodeStart(JsonOps.INSTANCE, WAYPOINTS).getOrThrow(), writer);
+		try (BufferedReader reader = Files.newBufferedReader(PATH)) {
```
Comment (AzureAaron) [inline src/main/java/de/hysky/skyblocker/skyblock/waypoint/OrderedWaypoints.java:73]: Is there a reason for making this not blocking now that it doesn't really do much?

File: src/main/resources/assets/skyblocker/lang/en_us.json
Comment (AzureAaron) [inline src/main/resources/assets/skyblocker/lang/en_us.json:1]: If the ordered waypoint commands are removed then their translation strings should also be removed.

**Review by AzureAaron — CHANGES_REQUESTED** [review]

File: src/main/java/de/hysky/skyblocker/skyblock/waypoint/OrderedWaypoints.java (hunk 1 above)
Comment (kevinthegreat1) [reply src/main/java/de/hysky/skyblocker/skyblock/waypoint/OrderedWaypoints.java:53]: Yeah, this was not rebased. The init annotation wasn't actually touched.

File: src/main/java/de/hysky/skyblocker/skyblock/waypoint/OrderedWaypoints.java (hunk 2 above)
Comment (kevinthegreat1) [reply src/main/java/de/hysky/skyblocker/skyblock/waypoint/OrderedWaypoints.java:73]: This is so that `migrateOrderedWaypoints` is called synchronously to prevent race conditions with waypoints.

File: src/main/resources/assets/skyblocker/lang/en_us.json
Comment (kevinthegreat1) [reply src/main/resources/assets/skyblocker/lang/en_us.json:1]: Done.

**Comment by kevinthegreat1** [comment]
Closes #1024.

File: src/main/resources/assets/skyblocker/lang/en_us.json
Comment (AzureAaron) [inline src/main/resources/assets/skyblocker/lang/en_us.json:1]: Since the text scale options are no longer used their translation keys should be removed.

**Review by AzureAaron — CHANGES_REQUESTED** [review]

**Review by AzureAaron — CHANGES_REQUESTED** [review]
Incase you forgot just change the ordered waypoints migrator so that it imports under both dwarven mines & CH and then this is good to go

**Review by AzureAaron — APPROVED** [review]
