### PR TITLE
Garden fixes

### LINKED ISSUE #1270: Visitor Helper Bug
### What happened?

Visitor Helper isnt working for the first two visitors.

### Screenshots

_No response_

### Log output

[latest.log](https://github.com/user-attachments/files/20129793/latest.log)

### Minecraft Version

1.21.5

### Skyblocker Version

skyblocker-5.2.0+1.21.5.jar

### Additional context

Im using the latest version of the modpack, Skyblocker Modpack - Hypixel Skyblock 3.5.0.

### PR DESCRIPTION
**Pull request by LifeIsAParadox**
fixes #1270 
### Garden Plot Widget
- Fixed the garden plot widget not being clickable
- Inventory status effects are now hidden while the garden plot widget is active

before:

after:

### Farming Hud
- You can now choose between NPC, Bazaar, or Both for calculating coin/h
- The HUD now shows which pricing source is being used (Bazaar or NPC)

### Visitor
- Added a `copyAndOpenBazaar` option (default: `true`) – clicking the item opens the Bazaar and copies the amount
- Re-added underline on hovered text for better clarity

Bildschirmfoto vom 2025-05-11 23-00-21

### CODE REVIEW

File: src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java [hunk 1]
```diff
@@ -36,6 +36,7 @@ public class VisitorHelper {
 	private static final int ICON_SIZE = 16;
 	private static final int LINE_HEIGHT = 3;
 	private static final ItemStack BARRIER = new ItemStack(Items.BARRIER);
+	private static final Map<Text, Long> copiedTimestamps = new HashMap<>();
```
Comment (viciscat) [inline src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java:39]: `Object2LongMap` :)

File: src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java [hunk 2]
```diff
@@ -219,28 +237,38 @@ public static void handleMouseClick(double mouseX, double mouseY, int mouseButto
...
+				boolean copyAndOpenBz = SkyblockerConfigManager.get().farming.visitorHelper.copyAndOpenBz;
 
 				if (isMouseOverText(mouseX, mouseY, textX, yPosition, itemTextWidth, textRenderer.fontHeight)) {
 					MessageScheduler.INSTANCE.sendMessageAfterCooldown("/bz " + itemName.getString(), true);
+
+					if (copyAndOpenBz) {
+						MinecraftClient client = MinecraftClient.getInstance();
+						client.keyboard.setClipboard(String.valueOf(totalAmount));
+						if (client.player != null) {
+							client.player.sendMessage(Constants.PREFIX.get().append(Text.translatable("skyblocker.config.farming.general.copiedAmountSuccessfully")), false);
```
Comment (viciscat) [inline src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java:258]: Not sure if this is really needed

File: src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java [hunk 3]
```diff
@@ -219,28 +237,38 @@ public static void handleMouseClick(double mouseX, double mouseY, int mouseButto
...
 					return;
 				}
 
-				if (isMouseOverText(mouseX, mouseY, copyTextX, yPosition, textRenderer.getWidth(" [Copy Amount]"), textRenderer.fontHeight)) {
+				if (!copyAndOpenBz && isMouseOverText(mouseX, mouseY, copyTextX, yPosition, textRenderer.getWidth(Text.translatable("skyblocker.config.farming.general.copyAmount")), textRenderer.fontHeight)) {
 					MinecraftClient client = MinecraftClient.getInstance();
 					client.keyboard.setClipboard(String.valueOf(totalAmount));
 					if (client.player != null) {
-						client.player.sendMessage(Constants.PREFIX.get().append("Copied amount successfully"), false);
+						client.player.sendMessage(Constants.PREFIX.get().append(Text.translatable("skyblocker.config.farming.general.copiedAmountSuccessfully")), false);
```
Comment (viciscat) [inline src/main/java/de/hysky/skyblocker/skyblock/garden/visitor/VisitorHelper.java:270]: again

File: src/main/resources/assets/skyblocker/lang/en_us.json [hunk 4]
```diff
@@ -258,6 +263,20 @@
...
+  "skyblocker.config.farming.visitorHelper.copyAndOpenBz.@Tooltip": "Copy amount and open bz",
+
+  "skyblocker.config.farming.general.cropsPerMin": "Crops/min: ",
+  "skyblocker.config.farming.general.coinsPerHour": "Coins/h: ",
+  "skyblocker.config.farming.general.blocksPerSec": "Blocks/s: ",
+  "skyblocker.config.farming.general.farmingLevel": "Farming Level:",
+  "skyblocker.config.farming.general.farmingXPPerHour": "Farming XP/h: ",
+  "skyblocker.config.farming.general.noCameraEntity": "No Camera Entity",
+  "skyblocker.config.farming.general.yaw": "Yaw: ",
+  "skyblocker.config.farming.general.pitch": "Pitch: ",
```
Comment (viciscat) [inline src/main/resources/assets/skyblocker/lang/en_us.json:276]: More of a `%s` guy instead of append but it doesn't really matter does it?

File: src/main/resources/assets/skyblocker/lang/en_us.json [hunk 5]
```diff
@@ -258,6 +263,20 @@
   "skyblocker.config.farming.visitorHelper.visitorHelperGardenOnly.@Tooltip": "Locks the Visitor Helper so it only works on the Garden.\n§cRequires Visitor Helper to be enabled.",
   "skyblocker.config.farming.visitorHelper.showStacksInVisitorHelper": "Show Stacks in Visitor Helper",
   "skyblocker.config.farming.visitorHelper.showStacksInVisitorHelper.@Tooltip": "Show's the required items as (5 stacks + 45) rather than just a total number especially useful for ironman players.",
+  "skyblocker.config.farming.visitorHelper.copyAndOpenBz": "Copy amount and open bz",
+  "skyblocker.config.farming.visitorHelper.copyAndOpenBz.@Tooltip": "Copy amount and open bz",
```
Comment (viciscat) [inline src/main/resources/assets/skyblocker/lang/en_us.json:267]: Useless tooltip?

File: src/main/resources/assets/skyblocker/lang/en_us.json [hunk 6]
```diff
@@ -244,6 +244,11 @@
   "skyblocker.config.farming.garden.dicerTitlePrevent": "Enable Dicer Title Prevent",
   "skyblocker.config.farming.garden.enableHud": "Enable Farming HUD",
   "skyblocker.config.farming.garden.farmingHud": "Farming HUD Config...",
+  "skyblocker.config.farming.garden.farmingHud.type": "Price Value from",
+  "skyblocker.config.farming.garden.farmingHud.type.@Tooltip": "Price Value from",
```
Comment (viciscat) [inline src/main/resources/assets/skyblocker/lang/en_us.json:248]: Useless tooltip?

**Review by viciscat — CHANGES_REQUESTED** [review]

**Review by kevinthegreat1 — APPROVED** [review]

**Review by viciscat — APPROVED** [review]
oops forgot to approve when i tested it

**Comment by Alex33856** [comment]
@kevinthegreat1 this is missing "import de.hysky.skyblocker.skyblock.tabhud.widget.component.IcoTextComponent;" in java\de\hysky\skyblocker\skyblock\tabhud\widget\ComponentBasedWidget.java

**Comment by kevinthegreat1** [comment]
Thanks for the help.
