### PR TITLE
emi/rei, Quicknav, livid and nukekubi head (eman boss head) fix

### LINKED ISSUE #378: Quick Nav not deselecting in when gui fails to open
### What happened?

The enchanting table and anvil tabs are selected even though they did not successfully open since I don't have a booster cookie.

### Screenshots

Screenshot 2023-10-20 at 23 13 50

### Log output

_No response_

### Minecraft Version

1.20.2

### Skyblocker Version

skyblocker-1.14.0-beta-a2dde4f+1.20.2

### Additional context

_No response_

### LINKED ISSUE #538: Correct Livid detector dies after Livid changes color
### What happened?

That one is rare to see as Livid changes color only if you take too long, but still
It works like this. Let's say, Livid is blue:
1. Livid is blue
2. You skill issue for a minute because this moron keeps teleporting
3. Black screen, Livid is now white - solver does not update color and does not highlight correct one 
4. There are also may be two Livids of same color (real one and fake one)??

### Screenshots

_No response_

### Log output

_No response_

### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.17.0-beta-7aaf222+1.20.4.jar

### Additional context

_No response_

### LINKED ISSUE #539: Livid solver breaks if server lags
### What happened?

2 bugs for one thing YAY

So thing at ceiling before fight starts is RED, but it changes when it starts. However, server sometimes lags and solver may say "color is RED" while real color is different

### Screenshots

_No response_

### Log output

_No response_

### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.17.0-beta-7aaf222+1.20.4.jar

### Additional context

_No response_

### LINKED ISSUE #860: Eman Slayer
### What happened?

Nukekubi heads highlighter doesn't work

### Screenshots

_No response_

### Log output

_No response_

### Minecraft Version

1.21.0

### Skyblocker Version

Skyblocker 1.21 alpha

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LifeIsAParadox**
fixes #378, fixes #539, fixes #538, fixes #860

# emi/rei fix
emi and rei are working again

# Quicknav
The click behavior of the Quicknavbutton has been changed so that it is more like a button click. The button is therefore pressed for 0.25 seconds. This has the advantage that the button can be pressed again if an error occurs. Otherwise, everything is the same, i.e. if the container name is recognized, it remains pressed and cannot be pressed again.
A fade animation has also been added.
outs3

# Livid
The logic of the livid code has been changed.
The system checks whether the current color is the same as the last found livid color. The initial color is detected after the first blindness effect + 2 seconds.
I also added the bounding box option for livid to make it easier to recognize the correct enemy. I changed default mob glow option to false by and bounding box option to true.
thanks to hysteria for testing stuff

# nukekubi head fix
the heads are now highlighted correctly again (to-do: only highlight your boss heads and not others)
changed the highlight color to green
thanks to hysteria for testing stuff

#  Slottext: Half-Eaten Carrot Collection
added support for Half-Eaten Carrot collection for slottext

### CODE REVIEW

**Comment by LifeIsAParadox** [comment]
yeah my bad I meant 0.25 and not 2.5.

**Comment by kevinthegreat1** [comment]
I would change it to at lease 1 second for ppl with ping in the hundreds lol

**Comment by LifeIsAParadox** [comment]
I get what you mean, but 1 second feels wrong. It looks weird. I chose 0.25 seconds because the key press feels best with that timing.

**Comment by kevinthegreat1** [comment]
This pr looks fine, why wip?

**Comment by minusHysteria** [comment]
wol was changing the eman skull glow to also use this bounding box, because the glow on that is broken as well

File: src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java [hunk 1]
```diff
@@ -44,37 +46,51 @@ public class LividColor {
...
-                    return;
-                }
-                tenTicks--;
-            } else {
-                tenTicks = 0;
+
+        if (!(Utils.isInDungeons() && DungeonManager.isInBoss() && client.player != null && client.world != null)) return;
+
+        Block currentColor = client.world.getBlockState(new BlockPos(5, 110, 42)).getBlock();
+        if (!(WOOL_TO_FORMATTING.containsKey(currentColor) && !currentColor.equals(lastColor))) return;
```
Comment (kevinthegreat1) [inline src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java:72]: Correct but a bit confusing.

File: src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java [hunk 2]
```diff
@@ -44,37 +46,51 @@ public class LividColor {
...
+                String lividName = LIVID_TO_FORMATTING.entrySet().stream()
+                        .filter(entry -> entry.getValue() == color)
+                        .map(Map.Entry::getKey)
+                        .findFirst()
+                        .orElse("unknown");
+                client.world.getPlayers().stream()
+                        .filter(entity -> entity.getName().getString().equals(lividName))
+                        .findFirst()
+                        .ifPresent(entity -> lividID = entity.getId());
+                originLividFound = true;
```
Comment (kevinthegreat1) [inline src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java:89]: I'm a bit confused. How does this work when livid changes color when it only runs on the first time?

Actually, this whole `lividId` thing seems kinda unnecessary since we're still checking the name and you could revert to the old `names.contains` check if you end up changing this.

File: src/main/java/de/hysky/skyblocker/skyblock/entity/MobGlow.java [hunk 3]
```diff
@@ -111,26 +110,27 @@ public static int getGlowColor(Entity entity) {
...
 	private static boolean isNukekubiHead(ArmorStandEntity entity) {
+		boolean armorfound = false;
 		for (ItemStack armorItem : entity.getArmorItems()) {
 			// eb07594e2df273921a77c101d0bfdfa1115abed5b9b2029eb496ceba9bdbb4b3 is texture id for the nukekubi head,
 			// compare against it to exclusively find armorstands that are nukekubi heads
 			// get the texture of the nukekubi head item itself and compare it
 			String texture = ItemUtils.getHeadTexture(armorItem);
 
-			return texture.contains("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWIwNzU5NGUyZGYyNzM5MjFhNzdjMTAxZDBiZmRmYTExMTVhYmVkNWI5YjIwMjllYjQ5NmNlYmE5YmRiYjRiMyJ9fX0=");
+			armorfound |= texture.contains("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWIwNzU5NGUyZGYyNzM5MjFhNzdjMTAxZDBiZmRmYTExMTVhYmVkNWI5YjIwMjllYjQ5NmNlYmE5YmRiYjRiMyJ9fX0=");
```
Comment (kevinthegreat1) [inline src/main/java/de/hysky/skyblocker/skyblock/entity/MobGlow.java:132]: Well, this is a stupid bug... (Perfect opportunity for stream api btw.)

File: src/main/java/de/hysky/skyblocker/utils/NEURepoManager.java [hunk 4]
```diff
@@ -49,6 +51,20 @@ public static void init() {
                         }))
                 )
         );
+        SkyblockEvents.JOIN.register(NEURepoManager::load);
+    }
+
+    private static void load() {
```
Comment (kevinthegreat1) [inline src/main/java/de/hysky/skyblocker/utils/NEURepoManager.java:57]: Ideally, this could have a better name (and maybe javadoc) or else it's easy to think that this loads the neu repo.

**Review by kevinthegreat1 — DISMISSED** [review]

File: src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java (hunk 2 above)
Comment (LifeIsAParadox) [reply src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java:89]: The idea is to identify the original livid and use its ID to highlight the correct livid. The problem with the old variant is that the original Livid in M5 changes color, resulting in two Livids with the same color. Therefore, the only reliable identifier for the original Livid is its ID.

The code looks like that because i first need the livid name of the original livid and second go through all players in the area (in theory i could do 2 loops to get the info if you want it less confusing).

Comment (kevinthegreat1) [reply src/main/java/de/hysky/skyblocker/skyblock/dungeon/LividColor.java:89]: I see, I wasn't familiar with M5 mechanics. Thanks for clearing this up.

**Review by kevinthegreat1 — APPROVED** [review]
